# Use the official Node.js image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy source code
COPY . .

# Accept build arguments for Vite environment variables
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_SERVICE_ROLE_KEY
ARG VITE_API_URL
ARG VITE_WS_URL
ARG VITE_SERVER_URL
ARG VITE_APP_NAME
ARG VITE_ANDROID_PACKAGE
ARG VITE_ENABLE_ANDROID_FEATURES
ARG VITE_ENABLE_BLUETOOTH
ARG VITE_ENABLE_LOCAL_NETWORK
ARG VITE_DEFAULT_PRINTER_IP
ARG VITE_CLOUDINARY_CLOUD_NAME
ARG VITE_CLOUDINARY_API_KEY
ARG VITE_CLOUDINARY_API_SECRET

# Set them as environment variables for the build
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_SERVICE_ROLE_KEY=$VITE_SUPABASE_SERVICE_ROLE_KEY
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_WS_URL=$VITE_WS_URL
ENV VITE_SERVER_URL=$VITE_SERVER_URL
ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_ANDROID_PACKAGE=$VITE_ANDROID_PACKAGE
ENV VITE_ENABLE_ANDROID_FEATURES=$VITE_ENABLE_ANDROID_FEATURES
ENV VITE_ENABLE_BLUETOOTH=$VITE_ENABLE_BLUETOOTH
ENV VITE_ENABLE_LOCAL_NETWORK=$VITE_ENABLE_LOCAL_NETWORK
ENV VITE_DEFAULT_PRINTER_IP=$VITE_DEFAULT_PRINTER_IP
ENV VITE_CLOUDINARY_CLOUD_NAME=$VITE_CLOUDINARY_CLOUD_NAME
ENV VITE_CLOUDINARY_API_KEY=$VITE_CLOUDINARY_API_KEY
ENV VITE_CLOUDINARY_API_SECRET=$VITE_CLOUDINARY_API_SECRET

# Build the application
RUN npm run build:mobile

# Expose the port
EXPOSE 5000

# Set environment variables
ENV NODE_ENV=production
ENV PORT=5000

# Start the application
CMD ["npm", "run", "start:mobile"]
