# fly.toml app configuration file generated for antonio-app on 2025-08-20T00:00:00.000Z
app = "antonio-app"
primary_region = "ord"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  NODE_ENV = "production"
  PORT = "5000"
  HOST = "0.0.0.0"
