services:
  - type: web
    name: restaurant-backend
    env: node
    plan: free
    buildCommand: npm run build:mobile
    startCommand: npm run start:mobile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: your-database-name
    #     property: connectionString
